[application]

[web.app]
title = "Commeator"

[web.watcher]
index_on_404 = true
output = "dist"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[web.env]
BASE_URL_AUTH = "https://auth.example.com"
BASE_URL_API = "https://api.example.com"
