[application]
identifier = "org.commeator.app"
name = "Commeator"
version = "0.1.0"

[web.app]
title = "Commeator"

[web.watcher]
index_on_404 = true
output = "dist"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []
