dsn: memory

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

selfservice:
  default_browser_return_url: http://localhost:3000/auth/callback

  methods:
    password:
      enabled: false
    oidc:
      enabled: true
      config:
        providers:
          - id: google
            provider: google
            client_id: GOOGLE_CLIENT_ID
            client_secret: GOOGLE_CLIENT_SECRET
            mapper_url: "base64://bG9jYWwgY2xhaW1zID0gc3RkLmV4dFZhcigiY2xhaW1zIik7Cgpsb2NhbCBuYW1lID0gaWYgc3RkLm9iamVjdEhhcyhjbGFpbXMsICJnaXZlbl9uYW1lIikgfHwgc3RkLm9iamVjdEhhcyhjbGFpbXMsICJmYW1pbHlfbmFtZSIpIHRoZW4KICB7CiAgICBmaXJzdDogaWYgc3RkLm9iamVjdEhhcyhjbGFpbXMsICJnaXZlbl9uYW1lIikgdGhlbiBjbGFpbXMuZ2l2ZW5fbmFtZSBlbHNlICIiLAogICAgbGFzdDogaWYgc3RkLm9iamVjdEhhcyhjbGFpbXMsICJmYW1pbHlfbmFtZSIpIHRoZW4gY2xhaW1zLmZhbWlseV9uYW1lIGVsc2UgIiIsCiAgfQplbHNlIG51bGw7Cgpsb2NhbCB0cmFpdHMgPSB7CiAgbmFtZTogbmFtZSwKfTsKCmxvY2FsIHRyYWl0c193aXRoX2VtYWlsID0gaWYgc3RkLm9iamVjdEhhcyhjbGFpbXMsICJlbWFpbCIpICYmIGNsYWltcy5lbWFpbF92ZXJpZmllZAogIHRoZW4gdHJhaXRzICsgeyBlbWFpbDogY2xhaW1zLmVtYWlsIH0KICBlbHNlIHRyYWl0czsKCmxvY2FsIHRyYWl0c193aXRoX2hkID0gaWYgc3RkLm9iamVjdEhhcyhjbGFpbXMsICJoZCIpICYmIGNsYWltcy5lbWFpbF92ZXJpZmllZAogIHRoZW4gdHJhaXRzX3dpdGhfZW1haWwgKyB7IGhkOiBjbGFpbXMuaGQgfQogIGVsc2UgdHJhaXRzX3dpdGhfZW1haWw7Cgp7CiAgaWRlbnRpdHk6IHsKICAgIHRyYWl0czogdHJhaXRzX3dpdGhfaGQsCiAgfSwKfQo="
            scope:
              - email

  flows:
    registration:
      ui_url: http://localhost:3000/auth/login
      lifespan: 1h
      enable_legacy_one_step: true
    login:
      ui_url: http://localhost:3000/auth/login
      lifespan: 1h
    error:
      ui_url: http://localhost:3000/auth/error

serve:
  public:
    base_url: http://localhost:4433
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3000
      allowed_methods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
      allowed_headers: [Authorization, Content-Type, Accept, X-CSRF-Token]
      allow_credentials: true

  admin:
    base_url: http://localhost:4434/
