FROM rust:latest AS builder
WORKDIR /app

RUN rustup target add wasm32-unknown-unknown && \
    curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash && \
    cargo binstall dioxus-cli@0.7.0-rc.1 --locked -y
ENV PATH="/.cargo/bin:$PATH"

COPY utils ./utils
COPY config/utils/env utils/.env
COPY client ./client

RUN cd client && \
    dx build @client --web --release



FROM nginx:alpine

COPY --from=builder /app/client/target/dx/commeator/release/web/public/ /usr/share/nginx/html/
COPY config/web/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
