FROM rust:1 AS chef

RUN cargo install cargo-chef

WORKDIR /app

FROM chef AS planner
COPY utils ./client
COPY client ./client
RUN cd client && \
    cargo chef prepare --recipe-path recipe.json



FROM chef AS builder

COPY --from=planner /app/client/recipe.json client/recipe.json
COPY utils ./utils

RUN rm utils/.env

COPY config/utils/env utils/.env

RUN cd client && \
    cargo chef cook --release --recipe-path recipe.json
COPY client ./client

RUN curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

RUN cargo binstall dioxus-cli@0.7.0-rc.1 --locked -y

ENV PATH="/.cargo/bin:$PATH"

RUN cd client && \
    dx build @client --web --release



FROM nginx:alpine

COPY --from=builder /app/client/target/dx/commeator/release/web/public/ /usr/share/nginx/html/
COPY config/web/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
