apiVersion: apps/v1
kind: Deployment
metadata:
  name: centrifugo
  labels:
    app: centrifugo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centrifugo
  template:
    metadata:
      labels:
        app: centrifugo
    spec:
      containers:
        - name: centrifugo
          image: centrifugo/centrifugo:v6.4
          args: ["centrifugo", "--config", "/etc/config/centrifugo/config.yaml"]
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: centrifugo-config
              mountPath: /etc/config/centrifugo/config.yaml
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: centrifugo-config
          secret:
            secretName: centrifugo-config

---

apiVersion: v1
kind: Service
metadata:
  name: centrifugo
  labels:
    app: centrifugo
spec:
  selector:
    app: centrifugo
  ports:
    - name: public
      port: 9000
      targetPort: 9000
  type: ClusterIP
