apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-env
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
              readOnly: true
      volumes:
        - name: postgres-env
          secret:
            secretName: postgres-env
        - name: postgres-init
          configMap:
            name: postgres-init
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: public
      port: 5432
      targetPort: 5432
  type: ClusterIP

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init.sql: |
    DO
    $$
    BEGIN
       IF NOT EXISTS (SELECT FROM pg_database WHERE datname = 'messenger') THEN
          PERFORM dblink_exec('dbname=postgres', 'CREATE DATABASE messenger');
       END IF;
    END
    $$;
    
    -- Create user if not exists
    DO
    $$
    BEGIN
       IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'messenger') THEN
          CREATE USER messenger WITH ENCRYPTED PASSWORD 'messenger';
       END IF;
    END
    $$;
    
    -- Grant privileges
    GRANT ALL PRIVILEGES ON DATABASE messenger TO messenger;
    
    -- Enable uuid-ossp extension
    \connect messenger
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
