apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: commeator-web:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          volumeMounts:
            - name: endpoints
              mountPath: /usr/share/nginx/html/endpoints.json
              subPath: endpoints.json
              readOnly: true
      volumes:
        - name: endpoints
          secret:
            secretName: endpoints
