client:
  token:
    hmac_secret_key: "YOUR_SECRET_KEY"
  allowed_origins:
    - http://localhost
    - http://localhost:8000
    - http://localhost:3000
    - http://server:3000

http_api:
  key: "YOUR_SECRET_KEY"

http_server:
  port: 9000

admin:
  enabled: true
  password: "YOUR_PASSWORD"
  secret: "YOUR_SECRET_KEY"

websocket:
  disabled: false
  compression: false

engine:
  type: memory
