//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "chats")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: Uuid,
    pub is_group: bool,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chat_members::Entity")]
    ChatMembers,
    #[sea_orm(has_many = "super::chat_names::Entity")]
    ChatNames,
    #[sea_orm(has_many = "super::messages::Entity")]
    Messages,
}

impl Related<super::chat_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatMembers.def()
    }
}

impl Related<super::chat_names::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatNames.def()
    }
}

impl Related<super::messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Messages.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
