//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "chat_members")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub chat_uuid: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_uuid: Uuid,
    pub joined_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chats::Entity",
        from = "Column::ChatUuid",
        to = "super::chats::Column::Uuid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Chats,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserUuid",
        to = "super::users::Column::Uuid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::chats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chats.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
