//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::chat_members::Entity as ChatMembers;
pub use super::chat_names::Entity as ChatNames;
pub use super::chats::Entity as Chats;
pub use super::devices::Entity as Devices;
pub use super::messages::Entity as Messages;
pub use super::users::Entity as Users;
