name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clippy:
    name: Run lints
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dir: server
            features:
          - dir: client
            features: web
          - dir: utils
            features: server
          - dir: utils
            features: client
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev  libgtk2.0-dev libssl-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all-targets --features "${{ matrix.features }}" -- -D warnings
